(require 'meow)
(autoload 'er/expand-region "expand-region")
(autoload 'ace-window "ace-window")
(autoload 'undo-fu-only-undo "undo-fu")
(autoload 'undo-fu-only-redo "undo-fu")
(autoload 'vundo "vundo")

(defun meow-next-quickly ()
  (interactive)
  (next-line 5))

(defun meow-prev-quickly ()
  (interactive)
  (previous-line 5))

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-colemak)
  (meow-motion-overwrite-define-key
   ;; Use e to move up, n to move down.
   ;; Since special modes usually use n to move down, we only overwrite e here.
   '("e" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   '("?" . meow-cheatsheet)
   ;; To execute the originally e in MOTION state, use SPC e.
   '("e" . "H-e")
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("1" . meow-expand-1)
   '("2" . meow-expand-2)
   '("3" . meow-expand-3)
   '("4" . meow-expand-4)
   '("5" . meow-expand-5)
   '("6" . meow-expand-6)
   '("7" . meow-expand-7)
   '("8" . meow-expand-8)
   '("9" . meow-expand-9)
   '("-" . negative-argument)
   '("=" . er/expand-region)
   '(";" . meow-reverse)
   '("." . meow-inner-of-thing)
   '("," . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("{" . remember-init)
   '("}" . remember-jump)
   '("/" . meow-visit)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("e" . meow-prev)
   '("E" . meow-prev-quickly)
   ;; '("M-E" . meow-prev-expand)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-right)
   '("I" . meow-right-expand)
   '("j" . meow-join)
   '("k" . meow-kill)
   '("l" . meow-line)
   '("L" . meow-goto-line)
   '("m" . meow-mark-word)
   '("M" . meow-mark-symbol)
   '("n" . meow-next)
   '("N" . meow-next-quickly)
   ;; '("M-N" . meow-next-expand)
   '("o" . ace-window)
   '("O" . meow-block)
   '("p" . meow-yank)
   '("q" . meow-quit)
   '("r" . meow-replace)
   '("s" . meow-insert)
   '("S" . meow-open-above)
   '("t" . meow-till)
   '("u" . undo-fu-only-undo)
   '("U" . undo-fu-only-redo)
   '("v" . meow-search)
   '("V" . vundo)
   '("w" . meow-next-word)
   '("W" . meow-next-symbol)
   '("x" . delete-char)
   '("X" . meow-backward-delete)
   '("y" . meow-save)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("<escape>" . ignore)))

(meow-setup)
(meow-global-mode 1)

(setq
     meow-char-thing-table
     '((?\( . round)
       (?\) . round)
       (?\" .  string)
       (?\[ . square)
       (?\] . square)
       (?<  . angle)
       (?>  . angle)
       (?{  . curly)
       (?}  . curly)
       (?s  . symbol)
       (?f  . defun)
       (?w  . window)
       (?l  . line)
       (?b  . buffer)
       (?p  . paragraph)))


(provide 'init-meow)
